# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPQyci34P77Yc1GGoqypBSBys-eMWUJ1

# Statistics Basics Assignment
Assignment Code: DS-AG-005


1: What is the difference between descriptive statistics and inferential
statistics? Explain with examples.

ans. 1.It gives information about raw data which describes the data in some manner while It makes inferences about the population using data drawn from the population.

2.It helps in organizing, analyzing, and to present data in a meaningful manner while It allows us to compare data, and make hypotheses and predictions.

3.It is used to describe a situation while It is used to explain the chance of occurrence of an event.

4.Limited to presenting and analyzing known data.

while Allows predictions and conclusions that go beyond the data at hand.

Example -

Find the mode of the following data using descriptive statistics.
5, 6, 2, 7, 6, 5,1, 9, 5, 8, 5, 4, 3, 12, 11, 17, 5, 5

Solution: Mode is the most frequently occurring observation. Thus, the mode is 5

Answer: Mode = 5

Find the z score using descriptive and inferential statistics for the given data. Population mean 100, sample mean 120, population variance 49 and size 10.

Solution: Inferential statistics is used to find the z score of the data. The formula is given as follows:

z =
x
−
μ
σ

Standard deviation =
√
49
 = 7

z = (120 - 100) / 7

= 20 / 7 = 2.86

Answer: Z score = 2.86


2.What is sampling in statistics? Explain the differences between random
and stratified sampling

ans. Sampling in Statistics: Sampling is the process of selecting a subset of individuals or units from a
larger population to study and draw conclusions about the entire population. It is used when
studying the whole population is impractical, costly, or time-consuming. The goal is to obtain a
representative sample that reflects the population's characteristics.

Difference between random and stratified sampling:


Random sampling involves selecting individuals from a population where every member has an equal
chance of being chosen, typically using random number generators or lottery methods. While,
Stratified sampling divides the population into distinct subgroups (strata) based on specific
characteristics (e.g., age, gender, income), then randomly samples from each stratum, often
proportionally to the stratum’s size in the population.

3.Define mean, median, and mode. Explain why these measures of central
tendency are important.

ans. Mean, Median, and Mode are measures of central tendency used to summarize a set of data:

Mean: The average of all values (sum of values ÷ number of values).

Median: The middle value when the data is arranged in order.

Mode: The value that appears most frequently.

These measures help in understanding the general pattern or typical value in a dataset, making it
easier to compare and analyze data in fields like economics, education, health, and business

4.Explain skewness and kurtosis. What does a positive skew imply about the
data

ans. Skewness and kurtosis are statistical measures that describe the shape of a data distribution:

Skewness: Measures the asymmetry of the data.

Positive skewness means the tail on the right side is longer;

most values are concentrated on the left.

Kurtosis: Measures the "tailedness" or sharpness of the data peak.

High kurtosis = heavy tails and sharp peak.

Low kurtosis = light tails and flatter peak.

Positive skew implies that the data has a few high values pulling the mean to the right,
and the majority of the data is clustered to the left.

5.
Implement a Python program to compute the mean, median, and mode of
a given list of numbers.

numbers = [12, 15, 12, 18, 19, 12, 20, 22, 19, 19, 24, 24, 24, 26, 28]

(Include your Python code and output in the code box below.)

ans.
"""

numbers = [12, 15, 12, 18, 19, 12, 20, 22, 19, 19, 24, 24, 24, 26, 28]
import numpy as np
np.mean(numbers)

numbers = [12, 15, 12, 18, 19, 12, 20, 22, 19, 19, 24, 24, 24, 26, 28]
import numpy as np
np.median(numbers)

numbers = [12, 15, 12, 18, 19, 12, 20, 22, 19, 19, 24, 24, 24, 26, 28]
import numpy as np
from scipy import stats
stats.mode(numbers)

"""6. Compute the covariance and correlation coefficient between the following
two datasets provided as lists in Python:

list_x = [10, 20, 30, 40, 50]

list_y = [15, 25, 35, 45, 60]

(Include your Python code and output in the code box below.)

ans.


"""

list_x = [10, 20, 30, 40, 50]

list_y = [15, 25, 35, 45, 60]

x = np.array(list_x)
y = np.array(list_y)
cov_matrix = np.cov(x, y, bias=False) # Unbiased estimator (default)
cov_xy = cov_matrix[0, 1]
corr_matrix = np.corrcoef(x, y)
corr_xy = corr_matrix[0, 1]
print("Covariance:", cov_xy)
print("Correlation Coefficient:", corr_xy)

"""7. Write a Python script to draw a boxplot for the following numeric list and

identify its outliers. Explain the result:

data = [12, 14, 14, 15, 18, 19, 19, 21, 22, 22, 23, 23, 24, 26, 29, 35]

(Include your Python code and output in the code box below.)

ans.

"""

data = [12, 14, 14, 15, 18, 19, 19, 21, 22, 22, 23, 23, 24, 26, 29, 35]
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
sns.boxplot(data=data, orient='h')
plt.title("Boxplot of the Data")
plt.xlabel("Values")
plt.show()
Q1 = np.percentile(data, 25)
Q3 = np.percentile(data, 75)
QR = Q3 - Q1 # Corrected variable name: QR for Interquartile Range
lower_bound = Q1 - 1.5 * QR # Used QR instead of IQR
upper_bound = Q3 + 1.5 * QR # Used QR instead of IQR
outliers = [x for x in data if x < lower_bound or x > upper_bound]
print(f"Q1: {Q1}, Q3: {Q3}, IQR: {QR}") # Used QR instead of IQR
print(f"Lower Bound: {lower_bound}, Upper Bound: {upper_bound}")
print(f"Outliers: {outliers}")

"""8.You are working as a data analyst in an e-commerce company. The
marketing team wants to know if there is a relationship between advertising spend and daily sales.

Explain how you would use covariance and correlation to explore this
relationship.

Write Python code to compute the correlation between the two lists:

advertising_spend = [200, 250, 300, 400, 500]

daily_sales = [2200, 2450, 2750, 3200, 4000]

(Include your Python code and output in the code box below.)

ans.Covariance tells us the direction of the relationship:

If positive → when advertising spend increases, sales tend to increase.

If negative → when spend increases, sales tend to decrease.

However, magnitude is hard to interpret, as it's not standardized.

Correlation (usually Pearson's) tells us the strength and direction:

"""

advertising_spend = [200, 250, 300, 400, 500]

daily_sales = [2200, 2450, 2750, 3200, 4000]
# Convert to numpy arrays
x = np.array(advertising_spend)
y = np.array(daily_sales)
# Covariance
cov_matrix = np.cov(x, y, bias=False)
cov_xy = cov_matrix[0, 1]
# Correlation Coefficient
corr_matrix = np.corrcoef(x, y)
corr_xy = corr_matrix[0, 1]
# Print results
print(f"Covariance: {cov_xy}")
print(f"Correlation Coefficient: {corr_xy:.4f}")

"""9.Your team has collected customer satisfaction survey data on a scale of
1-10 and wants to understand its distribution before launching a new product.

Explain which summary statistics and visualizations (e.g. mean, standard
deviation, histogram) you’d use.

Write Python code to create a histogram using Matplotlib for the survey data:

survey_scores = [7, 8, 5, 9, 6, 7, 8, 9, 10, 4, 7, 6, 9, 8, 7]

(Include your Python code and output in the code box below.)

ans.
These help quantify the central tendency and spread of the data:

1. Mean (average) – Gives a central value.

2. Median – Useful if data is skewed.
3. Mode – Helps identify the most frequent score.
4. Standard deviation – Measures how spread out the data is.
5. Minimum and Maximum – Shows the range.
6. Count – Number of responses.

"""

import matplotlib.pyplot as plt
# Survey data
survey_scores = [7, 8, 5, 9, 6, 7, 8, 9, 10, 4, 7, 6, 9, 8, 7]
# Create histogram
plt.hist(survey_scores, bins=range(1, 12), edgecolor='black', align='left')
plt.title('Customer Satisfaction Survey Scores')
plt.xlabel('Score')
plt.ylabel('Frequency')
plt.xticks(range(1, 11))
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()